name: Workflow CD caller
on:
  pull_request:
    types: [closed]
    branches: 
      - 'main'
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      id: ${{ steps.get_id.outputs.id }} 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: traer id del artefacto
        uses: ./.github/ci-reusable-2.yml
      
  call-reusable-workflow:
    uses: ./.github/workflows/workflow_CD_reusable.yml
    needs: job1
    with:
      image-to-build: eperezstemdo/angulaimage:0.0.0-snapshot
      artifact_id: ${{ needs.job1.outputs.id }}
      
